val document = Document(1.0, "UTF-8", Entity("plano",""))
val curso = Entity("curso","Mestrado em Engenharia Informática")
val fuc1 = Entity("fuc", "")
val fuc2 = Entity("fuc", "")
val codigo1 = Attribute("codigo", "M4310")
val codigo2 = Attribute("codigo", "03782")
val nome1 = Entity("nome", "Programação Avançada")
val nome2 = Entity("nome", "Dissertação")
val ects1 = Entity("ects", "6.0")
val ects2 = Entity("ects", "42.0")
val avaliacao1 = Entity("avaliacao", "")
val avaliacao2 = Entity("avaliacao", "")
val componente1 = Entity("componente", "")
val componente2 = Entity("componente", "")
val componente3 = Entity("componente", "")
val componente4 = Entity("componente", "")
val componente5 = Entity("componente", "")
val nome11 = Attribute("nome", "Quizzes")
val nome22 = Attribute("nome", "Projeto")
val nome33 = Attribute("nome", "Dissertação")
val nome44 = Attribute("nome", "Apresentação")
val nome55 = Attribute("nome", "Discussão")
val peso1 = Attribute("peso", "20")
val peso2 = Attribute("peso", "80")
val peso3 = Attribute("peso", "60")

fun main() {
    fuc1.addAttribute(codigo1)
    fuc2.addAttribute(codigo2)
    componente1.addAttribute(nome11)
    componente2.addAttribute(nome22)
    componente3.addAttribute(nome33)
    componente4.addAttribute(nome44)
    componente5.addAttribute(nome55)
    componente1.addAttribute(peso1)
    componente2.addAttribute(peso2)
    componente3.addAttribute(peso3)
    componente4.addAttribute(peso1)
    componente5.addAttribute(peso1)
    avaliacao1.addEntityChild(componente1)
    avaliacao1.addEntityChild(componente2)
    avaliacao2.addEntityChild(componente3)
    avaliacao2.addEntityChild(componente4)
    avaliacao2.addEntityChild(componente5)
    fuc1.addEntityChild(nome1)
    fuc2.addEntityChild(nome2)
    fuc1.addEntityChild(ects1)
    fuc2.addEntityChild(ects2)
    fuc1.addEntityChild(avaliacao1)
    fuc2.addEntityChild(avaliacao2)
    document.addEntity(curso)
    document.addEntity(fuc1)
    document.addEntity(fuc2)
    document.writeToFile("XML File.txt")
    println(document.toXMLString())
}
